// RÃ©cupÃ©ration des informations de connexion (email + mot de passe)
document
  .getElementById("loginForm")
  .addEventListener("submit", async (event) => {
    event.preventDefault(); // EmpÃªche la soumission par dÃ©faut du formulaire

    const email = document.getElementById("email-login").value;
    const password = document.getElementById("password-login").value;

    try {
      console.log(
        "Tentative de connexion avec email:",
        email,
        "et mot de passe:",
        password
      ); // console.log Ã  supprimer Ã  la fin du projet et sa mise en ligne

      // Envoi des donnÃ©es au serveur pour l'authentification
      const response = await fetch("http://localhost:5678/api/users/login", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ email, password }),
      });

      console.log("RÃ©ponse du serveur:", response);

      if (response.ok) {
        // console.log("ðŸš€ ~ .addEventListener ~ response:", response);
        console.log("Connexion rÃ©ussie");
        let data = await response.json();
        localStorage.setItem("token", JSON.stringify(data));

        // L'utilisateur est connectÃ© avec succÃ¨s et est redirigÃ© vers index.html
        window.location.href = "index.html";
        console.log("ðŸš€ ~ .addEventListener ~ data:", data);
      } else {
        // Si le serveur renvoie une erreur, cela lance le message d'erreur
        const errorData = await response.json();
        throw new Error(errorData.message);
      }
    } catch (error) {
      // Affichage du message d'erreur
      console.error("Erreur lors de la connexion :", error.message);
      // Modification du contenu de #error-message
      document.getElementById("error-message").innerText =
        "Erreur lors de la connexion : " + error.message;
      // Pourquoi cela n'affiche que "Erreur lors de la connexion : user not found" quand
      // l'utilisateur est mauvais mais pas quand le mot de passe l'est lui aussi ?
    }
  });

// Ancien code avant modifications
/*try {
      // Envoi des donnÃ©es au serveur pour l'authentification
      const response = await fetch("http://localhost:5678/api/users/login", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ email, password }),
      });

      if (response.ok) {
        console.log("ðŸš€ ~ .addEventListener ~ response:", response);
        let data = await response.json();
        localStorage.setItem("token", data.token);

        console.log("ðŸš€ ~ .addEventListener ~ data:", data);
        // L'utilisateur est connectÃ© avec succÃ¨s et est redirigÃ© vers index.html
        window.location.href = "index.html";
      } else {
        // Si le serveur renvoie une erreur, cela lance le message d'erreur
        const errorData = await response.json();
        throw new Error(errorData.message);
      }
    } catch (error) {
      // Affichage du message d'erreur
      console.error("Erreur lors de la connexion :", error.message);
      // Modification du contenu de #error-message
      document.getElementById("error-message").innerText =
        "Erreur lors de la connexion : " + error.message;

      // Pourquoi cela n'affiche que "Erreur lors de la connexion : user not found" quand
      // l'utilisateur est mauvais mais pas quand le mot de passe est mauvais lui aussi ?
    }
  });
*/

// Code non fonctionnel : s'attend Ã  trouver un "try" Ã  la place de "catch" ligne 113
/*
    try {
      // Envoi des donnÃ©es au serveur pour l'authentification
      const response = await fetch("http://localhost:5678/api/users/login", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ email, password }),
      });

      if (response.ok) {
        console.log("ðŸš€ ~ .addEventListener ~ response:", response);
        let data = await response.json();
        localStorage.setItem("token", data.token);

        console.log("ðŸš€ ~ .addEventListener ~ data:", data);
        if (localStorage.getItem("token")) {
          // Masque le formulaire de connexion
          document.getElementById("login").style.display = "none";
          // L'utilisateur est connectÃ© avec succÃ¨s et est redirigÃ© vers index.html
          window.location.href = "index.html";
      } else {
        // Si le serveur renvoie une erreur, cela lance le message d'erreur
        const errorData = await response.json();
        throw new Error(errorData.message);
      }
    catch (error) {
      // Affichage du message d'erreur
      console.error("Erreur lors de la connexion :", error.message);
      // Modification du contenu de #error-message
      document.getElementById("error-message").innerText =
        "Erreur lors de la connexion : " + error.message;
    }
    }
  };
*/
